### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by maepopi** [metavoiceio/metavoice-src#101]
Hey there,

So I've tried installing and launching Metavoice on my Ubuntu 22.04 prior to finetuning, and I have a cascade of errors.

First, when I tried the quickstart I had this error:

`  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
`

I found on the net how to fix this (https://stackoverflow.com/questions/64662372/docker-compose-up-error-while-fetching-server-api-version-connection-aborte), but then after quite sometime the docker composing crashed and I had this :

```Creating metavoice-ui ... error

ERROR: for metavoice-ui  Cannot create container for service ui: unknown or invalid runtime name: nvidia

ERROR: for ui  Cannot create container for service ui: unknown or invalid runtime name: nvidia
ERROR: Encountered errors while bringing up the project.
```

I then moved on to the local installation. Everything seemed to go fine until I arrived at this line :
```poetry install && poetry run pip install torch==2.2.1 torchaudio==2.2.1```

Here, I had red lines saying this:
```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audiocraft 1.2.0 requires torch==2.1.0, but you have torch 2.2.0 which is incompatible.
fam 0.1.0 requires huggingface_hub<0.22.0,>=0.21.4, but you have huggingface-hub 0.20.3 which is incompatible.
torchaudio 2.1.0 requires torch==2.1.0, but you have torch 2.2.0 which is incompatible.
xformers 0.0.22.post7 requires torch==2.1.0, but you have torch 2.2.0 which is incompatible.
```

What should I do?

**Comment by vatsalaggarwal** [comment]
@lucapericlp

**Comment by maepopi** [comment]
and now when I try 
```poetry run python -i fam/llm/fast_inference.py```
I have this
```    import torch
  File "/home/maelys/anaconda3/envs/metavoice/lib/python3.10/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```
^^' maybe I should nuke everything and start over ?

**Comment by computersrmyfriends** [comment]
Same here.Installation fails to run. Followed the documentation "exactly step by step". Tried in fresh environments but does not work out of the box.
```

/metavoice-src/fam/llm/fast_inference_utils.py", line 131, in prefill
    logits = model(x, spk_emb, input_pos)
  File "/opt/conda/envs/metavoice/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by saurabh-kadian** [comment]
@maepopi 
For `xformers`, I referenced their [repo](https://github.com/facebookresearch/xformers) and used: `pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121`. Seems to work with 2.2.1

Still can't find a way to make `audiocraft` work with torch/torchaudio 2.2.1. 

Not sure if downgrading to 2.1.0 would work either, getting 
```
/torch/_dynamo/config_utils.py", line 72, in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
AttributeError: torch._inductor.config.fx_graph_cache does not exist
```

**Comment by maepopi** [comment]
Thank you @saurabh-kadian , I'm going to give it another try and keep you posted!

**Comment by lucapericlp** [comment]
Hey @maepopi, thanks for raising the issue! We recently added poetry dependency versioning which we'll need to improve docs around (amongst other changes possibly).

The red warning lines (related to audiocraft etc) are to be expected (we'll update the documentation to better reflect that) right now due to a few unfortunate dependency tangles. At that point, were you unable to run the `tts.synthesise`? In your later stacktrace, it seems like the conda env's `torch` is being used (you can be doubly sure that you're not using any conda envs via `conda deactivate`).

Could you `poetry env list`, take the relevant env & `poetry env remove {env-name}`, `conda deactivate` & then `poetry install && poetry run pip install torch==2.2.1 torchaudio==2.2.1`? You should be able to then run [the usage](https://github.com/metavoiceio/metavoice-src?tab=readme-ov-file#usage) commands successfully. If this isn't the case, let me know & I'll try my best to get you up & running again ASAP.

**Comment by lucapericlp** [comment]
Also thanks @saurabh-kadian, indeed we'll be pushing some updates soon in relation to this. It doesn't seem like it's the case but If you're experiencing any different issues, could I ask you to raise a separate issue?

**Comment by maepopi** [comment]
> Hey @maepopi, thanks for raising the issue! We recently added poetry dependency versioning which we'll need to improve docs around (amongst other changes possibly).
> 
> The red warning lines (related to audiocraft etc) are to be expected (we'll update the documentation to better reflect that) right now due to a few unfortunate dependency tangles. At that point, were you unable to run the `tts.synthesise`? In your later stacktrace, it seems like the conda env's `torch` is being used (you can be doubly sure that you're not using any conda envs via `conda deactivate`).
> 
> Could you `poetry env list`, take the relevant env & `poetry env remove {env-name}`, `conda deactivate` & then `poetry install && poetry run pip install torch==2.2.1 torchaudio==2.2.1`? You should be able to then run [the usage](https://github.com/metavoiceio/metavoice-src?tab=readme-ov-file#usage) commands successfully. If this isn't the case, let me know & I'll try my best to get you up & running again ASAP.

Hey! I am indeed using a conda environment. You know what, I'll just remove the environment and try reinstalling everything again from scratch and see how it goes!

**Comment by maepopi** [comment]
Hey again! So it worked indeed! I just removed the conda environment and restarted the installation from the "installation" section (not the docker commands). I still had these errors :

```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
audiocraft 1.2.0 requires torch==2.1.0, but you have torch 2.2.1 which is incompatible.
xformers 0.0.22.post7 requires torch==2.1.0, but you have torch 2.2.1 which is incompatible.
```

But I could go all the way up to tts.synthesise and I did have the output :)

I'm gonna try two things:
- Try @saurabh-kadian suggestion for xFormers
- Try the finetuning command

**Comment by saurabh-kadian** [comment]
Hey @lucapericlp, thanks for reverting back. I have opened another issue regarding installation. #106 
@maepopi, seems like you were able to inference using `tts.synthesise`, cheers !! 👍🏻.

**Comment by maepopi** [comment]
> Hey @lucapericlp, thanks for reverting back. I have opened another issue regarding installation. #106 @maepopi, seems like you were able to inference using `tts.synthesise`, cheers !! 👍🏻.

Yes thank you so much! I'm sorry to see that your problem has gone even more complex though...

**Comment by lucapericlp** [comment]
Great to hear that everyone seems to be sorted (& any related issues are also closed).

I'll close out this issue but feel free to open up any other issues if you bump into anything else where we might be able to help.

**Comment by nickmitchko** [comment]
I am not sure if this is completed, the dockerfile in main still causes an error due to` pip install torch==2.2.1`.

Anyone have a working dockerfile?
