### ISSUE TITLE
Small issue in finetuning

### ISSUE THREAD

**Issue by maepopi** [metavoiceio/metavoice-src#105]
Hey there, it's me again 😂

Okay I've gone ahead to try the finetuning as discussed [here](https://github.com/metavoiceio/metavoice-src/issues/35#issuecomment-1997498121). When launching the finetuning command, I had this error:

`
  File "/home/maelys/AI_PROJECTS/SOUND/TOOLS/metavoice-src/fam/llm/finetune.py", line 43, in <module>
    raise Exception(f"ckpts dir {ckpts_base_dir} does not exist!")
`
I went ahead and created the folder in question, and currently my model is training, but I thought I would raise the issue here because there might be an os.makedir(exist_ok=True) or similar line missing somewhere!

**Comment by sidroopdaska** [comment]
Did you try after pulling recent changes from `main`?
If so, @lucapericlp can you assist

**Comment by maepopi** [comment]
That seemed to do the trick! Thank you!
