### ISSUE TITLE
Using Metavoice when conda is installed?

### ISSUE THREAD

**Issue by computersrmyfriends** [metavoiceio/metavoice-src#118]
I have conda installed for other purposes to use other parts of my application. Is it possible to make Metavoice work when conda is present? 

I'm forced to keep conda. Please advise.

**Comment by lucapericlp** [comment]
Hey! Yep, you can use:

`poetry export -f requirements.txt --output requirements.txt`

& install from that to unblock yourself until we get https://github.com/metavoiceio/metavoice-src/pull/119 into `main`.

**Comment by computersrmyfriends** [comment]
Thank you so much! It was almost impossible before. It works now.
