### ISSUE TITLE
About semantic tokens

### ISSUE THREAD

**Issue by didadida-r** [metavoiceio/metavoice-src#127]
hi,

i am curious about the semantic token predicting, and what is the experient difference  or gen audio quality with & without adding semantic token?

'''skipped predicting semantic tokens as done in other works, as we found that this isn't strictly necessary'''

Thanks.

**Comment by vatsalaggarwal** [comment]
Hi, we haven't released any models that predict semantic tokens... in the end, we released this model as it required running one fewer model...
