### ISSUE TITLE
difference between fast_model.py and model.py

### ISSUE THREAD

**Issue by asultanoff** [metavoiceio/metavoice-src#129]
Hey everyone! I'm totally new to transformers and just starting to wrap my head around how everything works in this repo. I've been trying to understand the differences between the fast_model and the original GPT model, especially because the fast_model seems to have a different structure.
So, here's what I'm wondering: if the fast_model's transformer structure is different from the original GPT, does that mean the pre-trained weights provided for the GPT model won't work with the new architecture? Or are the weights actually intended for the new fast_model structure?
I'm guessing that maybe the weights are compatible because the overall idea of a transformer is still the same, but I'm not sure how the differences in the details might affect things. Could someone shed some light on this and explain if the provided weights can be used with the fast_model or if we need different weights for it? Thanks!

**Comment by vatsalaggarwal** [comment]
Both are slightly different implementations of the exact same model... the gpt_fast implementation is more compatible with torch.compile hence gives us an inference speedup... the weights are the exact same, but the naming convention can be slightly different, so we have to do very light "model surgery" to fix that
