### ISSUE TITLE
Generation issues with inputs which contain commas, punctuation, and ellipsis

### ISSUE THREAD

**Issue by somewheresy** [metavoiceio/metavoice-src#130]
When inputs contain commas and periods, the output generations often create too much interstitial space / silence between words before and after the characters.

When ellipsis are present in the input, instead of creating more interstitial space (silence), the model tends to hallucinate.

Could this be from removal of characters in the 100K hour training set?

**Comment by vatsalaggarwal** [comment]
Are you able to share some of the texts?

**Comment by lucapericlp** [comment]
Thanks for the update @somewheresy & sorry for the delay in my response - I'll go ahead & close out the issue but feel free to reopen if there's anything else to raise.
