### ISSUE TITLE
docker fails - invalid runtime nvidia

### ISSUE THREAD

**Issue by StarkBotha** [metavoiceio/metavoice-src#144]
docker-compose up -d server && docker-compose ps && docker-compose logs -f
[+] Running 0/0
 - Container metavoice-server  Creating                                                                            0.0s
Error response from daemon: unknown or invalid runtime name: nvidia

Windows 10 - Powershell

**Comment by CaptainJeff** [comment]
@StarkBotha same issue here

**Comment by sidroopdaska** [comment]
We don't have a windows env atm. Would greatly appreciate a PR from either of you :)

**Comment by CaptainJeff** [comment]
@sidroopdaska i'm actually using an macbook pro

**Comment by lucapericlp** [comment]
Hey @CaptainJeff @StarkBotha, thanks for raising, I'm gonna close this issue given its out of the scope of our current support but I've created an explicit feature request issue that we can use to track in the future.

**Comment by Ty-Wattana** [comment]
In docker-desktop in Setting --> Docker Engine: I change the JSON Docker daemon config file to 

{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "runtimes": {
    "nvidia": {
      "path": "/usr/bin/nvidia-container-runtime",
      "runtimeArgs": []
    }
  }
}

and it works for me
