### ISSUE TITLE
صدای دخترانه

### ISSUE THREAD

**Issue by HASHMATU** [metavoiceio/metavoice-src#146]
سلام #132 خوب هستی صحتمند

**Comment by HASHMATU** [comment]
> سلام #132 خوب هستی صحتمند

الحمدالله خودت خوب هستی

**Comment by HASHMATU** [comment]
طرفای تان خیریتی است

**Comment by lucapericlp** [comment]
Thanks for the issue, we'll be updating that issue with an updated PR shortly. If you have any other issues, feel free to raise a new issue.
