### ISSUE TITLE
You banned me in the discord for jokingly asking if I could use this for fraud and I'm just curious...

### ISSUE THREAD

**Issue by jdbohrman** [metavoiceio/metavoice-src#154]
You realise that it's OSS so like....I can just do it anyways right? Assuming I was serious. Anyways. Great tone recognition lol. Feel like if you're going to make a model OSS you can't be upset if people wanna use it for things you find not kosher :3

**Comment by Tristan-Hopkins** [comment]
awww poor baby.

**Comment by jdbohrman** [comment]
> awww poor baby.

I mean, this was a question, not a complaint. Again, anyone can fork this :3

**Comment by Vitalii953** [comment]
yeah you deserved that and he was very nice to you i would say
