### ISSUE TITLE
Improving the latency

### ISSUE THREAD

**Issue by alxiang** [metavoiceio/metavoice-src#28]
Is improving the latency of the model on the roadmap, e.g. real-time TTS?

**Comment by sidroopdaska** [comment]
It is certainly on the roadmap! Out of interest, what are you building with TTS today? What latency are you looking for?

**Comment by alxiang** [comment]
We're building Lifelike, a voice AI character platform (https://lifelike.app), so we'd need latency < 500ms (the lower the better). If there's any way we can contribute to that effort over the next few months, would love to follow up over email (founders@lifelike.app)

**Comment by sidroopdaska** [comment]
Thanks for offering to help, we would love contributions! I have emailed you for an intro call.
Btw, I tried to use your platform, but got waitlisted :)

**Comment by gad2103** [comment]
Would also be willing to help! gabe@slang.ai

**Comment by sidroopdaska** [comment]
@gad2103, I have emailed you :)

**Comment by athenasaurav** [comment]
Hello @sidroopdaska 

Would love to contribute too. Please reach out to me at kumar@vodex.ai

**Comment by sidroopdaska** [comment]
@athenasaurav, I have emailed you

**Comment by vatsalaggarwal** [comment]
hey folks, try https://github.com/metavoiceio/metavoice-src/pull/71 ... it's a bit dirty, but does give a 2-4x speedup (depending on hardware)!

**Comment by vatsalaggarwal** [comment]
Closing due to resolution
