### ISSUE TITLE
Please freeze requirements and specify Python version

### ISSUE THREAD

**Issue by paulrogov** [metavoiceio/metavoice-src#32]
Guys, please specify Python version that you've tested and specific versions of `requirements.txt`.    

`pip3 freeze > requirements.txt`

I had to install 3 copies of `xformers`:

![xformers](https://github.com/metavoiceio/metavoice-src/assets/1624921/685c6bf6-2c4b-4953-9782-67ef2afea208)

**Comment by sidroopdaska** [comment]
Woops, sorry about that. I will do this shortly

**Comment by sidroopdaska** [comment]
@paulrogov, I have specified python version under #34. Hesitant to push a frozen requirements.txt since it will be _very_ verbose. Why isn't this standard practice with other OS project? Am I missing something?
