### ISSUE TITLE
Speech to Speech example

### ISSUE THREAD

**Issue by platform-kit** [metavoiceio/metavoice-src#43]
The studio has speech-to-speech (voice conversion). Presumably that is possible with the OSS model?

If so, I'd love to see a few lines of code demonstrating how it can be done.

**Comment by vatsalaggarwal** [comment]
Hi, speech-to-speech isn't supported via this model and is out of scope for this repository...

**Comment by nicolesimon13** [comment]
Would love speech to speech too - or if not, maybe a variation of tuning it with my voice and a mixture of something different. I would like to generate audio for a project I do not want associated directly with my voice. It is my content and not fraudulent - I just like some anonymity. Speech to Speech would be perfect but text to speech works fine - if we could change the voice.
