### ISSUE TITLE
Any chances for lower VRAM or MacOS versions?

### ISSUE THREAD

**Issue by PawelSzpyt** [metavoiceio/metavoice-src#54]
It would make it much more accessible for experimenting with it.

**Comment by sidroopdaska** [comment]
When you say lower VRAM, what kind of GPUs did you have in mind?

**Comment by PawelSzpyt** [comment]
Well, 4060 TI is cheap and can have 16GB VRAM. I was planning on buying a laptop with 3080 and 16GB VRAM, and running metavoice could be a better alternative to StyleTTS2 - if I could run it there. Halving the current requirements could open many more options from RTX 30 and 40 series. I believe people try to repurpose any hardware they have for AI usage, there is limited stock of 3090s and 4090s.

**Comment by sidroopdaska** [comment]
Please refer to #1 for Mac Support :)
