### ISSUE TITLE
Acknowledgement 

### ISSUE THREAD

**Issue by CreativeSelf0** [metavoiceio/metavoice-src#55]
Hey I found your speaker encoder code is similar to [Link](https://github.com/resemble-ai/Resemblyzer/blob/master/resemblyzer/voice_encoder.py) this code.

Can you please credit them?

**Comment by vatsalaggarwal** [comment]
Hey, we missed acknowledgement for the speaker encoder, thanks! btw, it was taken from https://github.com/liusongxiang/ppg-vc/blob/main/speaker_encoder/inference.py

**Comment by CreativeSelf0** [comment]
No worries, by all means. I just love to credit people's work. Anyways, amazing work!
