### ISSUE TITLE
Will it natively support other languages?

### ISSUE THREAD

**Issue by faceair** [metavoiceio/metavoice-src#6]
I saw that the readme described the training data mainly in English, and I was worried that it would not learn the prosody in other languages, for example, the prosody in Chinese should be very different from English.
Will it be possible to learn other languages in the future just by fine-tuning?

**Comment by INF800** [comment]
s, please elaborate more on:

> Support for (cross-lingual) voice cloning with finetuning.
> We have had success with as little as 1 minute training data for Indian speakers.

Can you please share the Indian speakers examples code and TTS results?

**Comment by AndreaPi** [comment]
Joining the chorus here! I would like to fine-tune this for Italian speech2speech. Could you release a tutorial on how to do this?

**Comment by juangea** [comment]
I also want to raise this question, looking for spanish :)

The system looks fantastic.

**Comment by philpav** [comment]
Looking forward to multilingual support!

**Comment by juangea** [comment]
If there is some info on how to train the Lora and how to apply it, I’m all for it, in the end a LORA can be trained in consumer hardware like a 4099, isn’t it?

**Comment by MonojitBanerjee** [comment]
> > Will it be possible to learn other languages in the future just by fine-tuning?
> 
> @faceair / anyone else here for that matter - until we release the fine-tuning code, are you open to testing this hypothesis with a LoRA implementation? It would greatly benefit the community. Others can adopt it for different languages too :)
I can try that.

**Comment by bread-on-toast** [comment]
> > Will it be possible to learn other languages in the future just by fine-tuning?
> 
> @faceair / anyone else here for that matter - until we release the fine-tuning code, are you open to testing this hypothesis with a LoRA implementation? It would greatly benefit the community. Others can adopt it for different languages too :)

Sure, would be interested

**Comment by sidroopdaska** [comment]
Please give us a few days, and we will share a reference implementation for this

**Comment by vatsalaggarwal** [comment]
I've added some initial pointers to this here: https://github.com/metavoiceio/metavoice-src/issues/70#issuecomment-1957337895

**Comment by maepopi** [comment]
Would be interested for French LoRA here :)

**Comment by mzdk100** [comment]
Hope to support Chinese.

**Comment by vatsalaggarwal** [comment]
I'm closing this issue in favour of https://github.com/metavoiceio/metavoice-src/issues/70 where active work seems to be happening!
