### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by jojeyh** [metavoiceio/metavoice-src#7]
Following install instructions, when I run 
`pip install -r requirements` 
I get the error

```
Collecting flash-attn
  Using cached flash_attn-2.5.2.tar.gz (2.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tx9pk_0o/flash-attn_5537406baed04038937f619dc63a1f9f/setup.py", line 17, in <module>
          from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
      ModuleNotFoundError: No module named 'wheel'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Have tried installing via `pip install packaging` and also adding
```
[build-system]
requires = ["packaging"]
```
but does not fix.  

Running on Ubuntu 22.0.4 LTS 64-bit

**Comment by jojeyh** [comment]
Oops just realized it actually says `wheel` instead of `packaging`.  Regardless there is something going on with this package `flash-attn`.  It keeps not finding packages that are already installed.  Cannot find `torch` now that I've played around with it

**Comment by mallahyari** [comment]
It doesn't work on MacOS. Gives plenty of errors including "flash attention" which is not supported by Mac. "flash-attn" has been used in the source code so it gives error on Mac.

**Comment by sidroopdaska** [comment]
@jojeyh, can you share more details on your installation process? 
Are you using venv or conda to install the environment?
What OS?

**Comment by sidroopdaska** [comment]
@mallahyari, good catch! We don't support MPS & MLX yet. Inferencing on CPU will be extremely slow. I would therefore recommend you run the code on Linux + Nvidia GPU

**Comment by suraj2906** [comment]
For me after resolving a few errors, it is stuck on "Building wheel for flash-attn". The devs of flash-attn said that they do not know how to install for Windows.

**Comment by vatsalaggarwal** [comment]
Sorry about that folks! This is because we're using flash decoding... We do have the implementation for this in the code, but no code path to utilising torch attn which should work on Windows AND Mac (provided mps support exists for all the operations needed). If it's of interest to someone, I can add some pointers, let me know :)

**Comment by jojeyh** [comment]
Yeah I was trying to run on CPU on Ubuntu, too bad!  I was using venv just for reference.  I'm SO GPU POOR

**Comment by Enverex** [comment]
This failed for me too (Arch x86_64, clean Python VEnv). I installed Torch via pip first, tried again and it worked. Not sure why it doesn't get pulled in automatically.

**Comment by ahmetkca** [comment]
> @mallahyari, good catch! We don't support MPS & MLX yet. Inferencing on CPU will be extremely slow. I would therefore recommend you run the code on Linux + Nvidia GPU

Is it planned to support apple silicon by any chance in the future?

**Comment by sidroopdaska** [comment]
See the discussion on #1

**Comment by snehesht** [comment]
Running `pip install wheel` fixed the issue for me.

**Comment by sidroopdaska** [comment]
> Running pip install wheel && pip install -r requirements.txt fixed the issue for me.

Fixes the issue

@jojeyh, how were you setting up your env for metavoice - conda or venv?

**Comment by sidroopdaska** [comment]
> Running pip install wheel && pip install -r requirements.txt fixed the issue for me.

Fixes the issue

@jojeyh, how were you setting up your env for metavoice - conda or venv?
