### ISSUE TITLE
Do you have to clone the voice everytime?

### ISSUE THREAD

**Issue by Elsayed91** [metavoiceio/metavoice-src#76]
Lets assume I ran synthesize once, and it yielded a good result. How can I continue to use that voice without having to process it every time?  Maybe like a way to make voices included in the preset voices in the demo on https://ttsdemo.themetavoice.xyz/ ?

**Comment by AMpravc** [comment]
Revelando GTA 6: O Que Esperar do Novo Capítulo da Série

Introdução:

Abertura com imagens icônicas dos jogos anteriores da série GTA.
Narração: "Prepare-se para a próxima aventura épica no mundo do crime virtual. GTA está de volta com sua sexta edição e promete revolucionar o universo dos jogos de mundo aberto. Hoje, vamos explorar tudo o que sabemos sobre GTA 6."

1. Ambientação:
Apresentação das especulações e rumores sobre os possíveis locais do jogo, como Vice City e uma nova versão de Liberty City.
Destaque para as possíveis características únicas de cada localização.


2. Personagens e Enredo:
Discussão sobre os protagonistas e antagonistas prováveis, com base em vazamentos e teorias dos fãs.
Exploração das possíveis linhas de enredo e missões, com ênfase na narrativa imersiva e nas reviravoltas esperadas.

**Comment by AMpravc** [comment]
Top

**Comment by vatsalaggarwal** [comment]
@Elsayed91 does that help? are we good to close this issue?
