### ISSUE TITLE
Quantization Support?

### ISSUE THREAD

**Issue by gururise** [metavoiceio/metavoice-src#83]
Would like to quantize the model to 8 or 4-bit for running on GPU with 6GB of memory and for possible speed boost. Is this possible?

**Comment by vatsalaggarwal** [comment]
There will likely be impact on quality... you'll probably need to quantise the first stage and also swap out the multiband diffusion model with vocos. This should take down model weights from ~10-12GB to ~2.7GB.

Keep us updated, and do open a PR with any progress, and we'll try to help you along!

# quantisation

you can try the code at https://github.com/pytorch-labs/gpt-fast/blob/main/quantize.py#L528 and https://github.com/pytorch-labs/gpt-fast/blob/main/generate.py#L219 ... we've borrowed this code for the faster inference, so it should fit in nicely... 

# swapping out mbd (multiband diffusion) + dfn (deepfilternet)

I think currently the models weights take up:
- first stage (~5GB)
- second stage (~60MB)
- speaker encoder (~20MB)
- multiband diffusion + deep filter net (~5GB)

So replacing multiband diffusion with vocos (https://huggingface.co/charactr/vocos-encodec-24khz) should reduce the memory usage by another ~5GB

**Comment by danablend** [comment]
I'd be interested in contributing this in the future (few weeks from now) if nobody else does.

@gururise would you be interested in working on this?

**Comment by arthurwolf** [comment]
@danablend that would be amazing !

**Comment by vatsalaggarwal** [comment]
hey folks, int4/int8 weight only quantisation has been added here: https://github.com/metavoiceio/metavoice-src/pull/95 ... we're seeing 2x speedups for the first stage model with some degradation in quality.
