### ISSUE TITLE
AttributeError: torch._inductor.config.fx_graph_cache does not exist

### ISSUE THREAD

**Issue by bluusun** [metavoiceio/metavoice-src#88]
python3 -i fam/llm/fast_inference.py 
/usr/local/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 809/809 [00:00<00:00, 4.13MB/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 93.1M/93.1M [00:01<00:00, 90.0MB/s]
/usr/local/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
mbd_comp_8.pt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.58G/4.58G [00:50<00:00, 90.6MB/s]
Traceback (most recent call last):
  File "/root/metavoice-src/fam/llm/fast_inference.py", line 13, in <module>
    from fam.llm.fast_inference_utils import build_model, main
  File "/root/metavoice-src/fam/llm/fast_inference_utils.py", line 48, in <module>
    torch._inductor.config.fx_graph_cache = (
  File "/usr/local/lib/python3.10/site-packages/torch/_dynamo/config_utils.py", line 72, in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
AttributeError: torch._inductor.config.fx_graph_cache does not exist
>>>

**Comment by danablend** [comment]
@bluusun You are probably running a previous PyTorch version.

Have you tried with torch==2.2.1?

**Comment by vatsalaggarwal** [comment]
thanks @danablend ... @bluusun i'm closing this due to the above answer, and lack of response... feel free to reopen if it doesn't get resolved
