### ISSUE TITLE
Any timeline for fine tuning code

### ISSUE THREAD

**Issue by rishikksh20** [metavoiceio/metavoice-src#9]
I'm looking to finetune this model, as you mentioned that you will open source finetuning code, do you have any timeline in mind for that.
And if possible, please do provide some info regarding training dataset.

**Comment by sidroopdaska** [comment]
See my comment here #6

**Comment by rishikksh20** [comment]
@sidroopdaska I have worked with LLM based TTS in past specifically `WhisperSpeech`, I think the main issue with them is to adapt other than English languages as good as English language. I think LORA might the way to adapt but haven't test that.

**Comment by rishikksh20** [comment]
The Prosody of metavoice seems excellent, but output voice is not crisp, and background is not completely silence on pauses, I think it's easily understandable as you are using diffusion-based vocoder.
